# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SmashFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmashFit
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Pods for Facebook
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # Pods for Google Sign In
  pod 'GoogleSignIn'

end
